### ISSUE TITLE
Redirect to view page if no request parameters are present

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#6]
https://github.com/joseortiz9/WebLabs_itmo/blob/74a572a3dcfbeafbc684c21fccf04b5d980a3237/src/ru/students/lab/servlets/ControllerServlet.java#L13

**Comment by joseortiz9** [comment]
I don't really understand this issue because in the case the request params are null it catches the error and returns the main page showing the error alert

https://github.com/joseortiz9/WebLabs_itmo/blob/e00b7309b2c048fa6a847d4e20b277c1f7e2ba3c/src/ru/students/lab/servlets/ControllerServlet.java#L16-L25
